---
title: "Annual Meetings"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(here)

```

The CA/NV APTF holds an annual meeting to provide participants an opportunity to share new information and to discuss issues of concern.

# Upcoming Meeting

**2026 Meeting**: Jan 9--10, TBD

## *Previous Meetings*

 - 2025 Meeting: CSU Channel Islands, Camarillo, CA
   - [Agenda](pdfs/2025_APTF_Agenda_w_substitutions.pdf)
   - [Abstracts](pdfs/2025_APTF_Abstracts_Final.pdf)
 - 2024 Meeting: UC Merced, Merced, CA
   - [Agenda](pdfs/2024_APTF_Agenda_Final.pdf)
   - [Abstracts](pdfs/2024_APTF_Abstracts.pdf)
 - 2023 Meeting: Sebastopol, California
   - [Agenda](pdfs/2023_APTF_Agenda_Final.pdf)
   - [Abstracts](pdfs/2023_APTF_Abstracts.pdf)
 - 2022 Meeting: Cancelled (pandemic)
 - 2021 Meeting: Cancelled (pandemic)
 - 2020 Meeting: San Diego, California
   - [Agenda](pdfs/2020_APTF_Agenda_Final.pdf)
 - 2019 Meeting - Arcata, California
   - [Agenda](pdfs/2019_APTF_Agenda_Final.pdf)
 - 2018 Meeting - Auburn, California
   - [Agenda](pdfs/2018_APTF_Agenda_Final.pdf)
 - 2017 Meeting - Santa Barbara, California
   - [Agenda](pdfs/2017_APTF_Agenda_Final.pdf)
 - 2016 Meeting - Davis, California
   - [Agenda](pdfs/2016_APTF_Agenda_Final.pdf)
   - [Abstracts](pdfs/2016_APTF_Abstracts.pdf)
 - 2015 Meeting - Malibu, California
   - [Agenda](pdfs/2015_APTF_Agenda_Final.pdf)
   - [Abstracts](pdfs/2015_APTF_Abstracts.pdf)
 - 2014 Meeting - Beatty, Nevada
   - [Agenda](pdfs/2014_APTF_Agenda_Final.pdf)
   - [Abstracts](pdfs/2014_APTF_Abstracts.pdf)
 - 2013 Meeting - Arcata, California
   - [Agenda](pdfs/2013_APTF_Agenda_Final.pdf)
   - [Abstracts](pdfs/2013_APTF_Abstracts.pdf)
 - 2012 Meeting - Placerville, California
   - [Agenda](pdfs/2012_APTF_Agenda_Final.pdf)
 - 2011 Meeting - Yosemite National Park, California
   - [Agenda](pdfs/2011_APTF_Agenda_Final.pdf)
   - [Abstracts](pdfs/2011_APTF_Abstracts.pdf)
 - 2010 Meeting - No Meeting Held
 - 2009 Meeting - Bodega Bay, California
   - [Agenda](pdfs/2009_APTF_Agenda_Final.pdf)
   - [Abstracts](pdfs/2009_APTF_Abstracts.pdf)
 - 2008 Meeting - San Diego, California
 - 2007 Meeting - Las Vegas, Nevada 
   - [Agenda](pdfs/2007_APTF_Agenda_Final.pdf)
   - [Abstracts](pdfs/2007_APTF_Abstracts.pdf)
 - 2006 Meeting - Arcata, California
 - 2005 Meeting - Berkeley, California
 - 2004 Meeting - Reno, Nevada
 - 2003 Meeting - Sacramento, CA
   - [Agenda](pdfs/2003_APTF_talks.pdf)
 - 2002 Meeting - San Diego, CA
   - [Agenda](pdfs/2002_APTF_talks.pdf)
 - 2001 Meeting - Sacramento, CA
   - [Agenda](pdfs/2001_APTF_talks.pdf)
   
   